export const SERVICE_PRICING = {
    currency: 'EUR',
    market: 'Bulgaria',
    reviewedAt: '2026-09-10',
    oneOff: [
        {
            id: 'automated-health-checks',
            name: 'Automated Web Health checks',
            priceFrom: 0,
            priceTo: 0,
            description: 'Self-service Website Inspector, Site Crawl, Accessibility and Email Domain Security checks.',
        },
        {
            id: 'manual-audit-review',
            name: 'Manual audit review',
            priceFrom: 49,
            priceTo: 49,
            description: 'Human review of automated findings with priorities and a concise action plan.',
        },
        {
            id: 'keyword-research',
            name: 'Keyword research & intent map',
            priceFrom: 69,
            priceTo: 69,
            description: 'Focused keyword set, intent grouping and recommended target pages for a small or local business.',
        },
        {
            id: 'competitor-snapshot',
            name: 'Competitor SEO snapshot',
            priceFrom: 79,
            priceTo: 79,
            description: 'Search visibility, keyword and content-gap snapshot for selected competitors.',
        },
        {
            id: 'backlink-review',
            name: 'Backlink profile review',
            priceFrom: 79,
            priceTo: 79,
            description: 'Backlink overview, risk signals and practical acquisition opportunities without paid placements.',
        },
        {
            id: 'local-seo-setup',
            name: 'Local SEO setup',
            priceFrom: 99,
            priceTo: 99,
            description: 'Local search checklist, Google Business Profile guidance and on-site local signals.',
        },
        {
            id: 'technical-seo-audit',
            name: 'Technical SEO audit + action plan',
            priceFrom: 119,
            priceTo: 119,
            description: 'Technical crawl review, indexability, metadata, internal linking and implementation priorities.',
        },
        {
            id: 'on-page-cleanup',
            name: 'On-page SEO setup / cleanup',
            priceFrom: 129,
            priceTo: null,
            description: 'Implementation on priority pages. Final quote depends on page count, CMS and access availability.',
        },
        {
            id: 'remediation-sprint',
            name: 'Full remediation sprint',
            priceFrom: 249,
            priceTo: null,
            description: 'Bundled technical remediation across multiple findings. Scope is confirmed after manual review.',
        },
    ],
    monthly: [
        {
            id: 'monitor',
            name: 'Monitor',
            price: 89,
            description: 'Rank and technical monitoring, monthly summary and priority alerts. No implementation included.',
        },
        {
            id: 'starter',
            name: 'Starter',
            price: 149,
            description: 'For small/local sites: monitoring, keyword tracking, technical follow-up and light on-page work.',
        },
        {
            id: 'growth',
            name: 'Growth',
            price: 249,
            description: 'Adds competitor, backlink and keyword-gap review plus a larger monthly optimization allowance.',
        },
        {
            id: 'pro',
            name: 'Pro',
            price: 399,
            description: 'For larger or e-commerce projects needing broader tracking, implementation and priority support.',
        },
    ],
    websiteBuilds: [
        { id: 'landing', name: 'Landing page', priceFrom: 199, description: 'A focused one-page site for a campaign, service or product.' },
        { id: 'portfolio', name: 'Portfolio', priceFrom: 299, description: 'A personal or creative portfolio with project presentation and contact flow.' },
        { id: 'business', name: 'Business website', priceFrom: 399, description: 'A professional small-business website with core pages, enquiry flow and basic SEO setup.' },
        { id: 'blog', name: 'Blog / publication', priceFrom: 449, description: 'A structured publishing website with categories, authoring and search-ready content templates.' },
        { id: 'store', name: 'Online store', priceFrom: 749, description: 'Product catalogue, cart and checkout foundation. Products and payment integrations affect scope.' },
        { id: 'custom', name: 'Custom web platform', priceFrom: 990, description: 'A tailored application, portal or workflow requiring discovery and a manually confirmed scope.' },
    ],
    exclusions: [
        'Paid media, sponsored placements and paid backlinks are not included.',
        'Long-form content production and translation are quoted separately.',
        'Unusually high third-party data/API usage is confirmed before chargeable work starts.',
        'Final pricing is confirmed after scope review; applicable taxes are shown on the final quote or invoice.',
    ],
} as const;
