export const SERVICE_PRICING = {
    currency: 'EUR',
    market: 'Bulgaria',
    reviewedAt: '2026-09-12',
    oneOff: [
        {
            id: 'automated-health-checks',
            name: 'Automated Web Health checks',
            priceFrom: 0,
            priceTo: 0,
            description: 'Self-service Website Inspector, Site Crawl, Accessibility and Email Domain Security checks.',
        },
        {
            id: 'manual-audit-review',
            name: 'Manual audit review',
            priceFrom: 49,
            priceTo: 49,
            description: 'Human review of automated findings with priorities and a concise action plan.',
        },
        {
            id: 'keyword-research',
            name: 'Keyword research & intent map',
            priceFrom: 69,
            priceTo: 69,
            description: 'Focused keyword set, intent grouping and recommended target pages for a small or local business.',
        },
        {
            id: 'competitor-snapshot',
            name: 'Competitor SEO snapshot',
            priceFrom: 79,
            priceTo: 79,
            description: 'Search visibility, keyword and content-gap snapshot for selected competitors.',
        },
        {
            id: 'backlink-review',
            name: 'Backlink profile review',
            priceFrom: 79,
            priceTo: 79,
            description: 'Backlink overview, risk signals and practical acquisition opportunities without paid placements.',
        },
        {
            id: 'local-seo-setup',
            name: 'Local SEO setup',
            priceFrom: 99,
            priceTo: 99,
            description: 'Local search checklist, Google Business Profile guidance and on-site local signals.',
        },
        {
            id: 'technical-seo-audit',
            name: 'Technical SEO audit + action plan',
            priceFrom: 119,
            priceTo: 119,
            description: 'Technical crawl review, indexability, metadata, internal linking and implementation priorities.',
        },
        {
            id: 'on-page-cleanup',
            name: 'On-page SEO setup / cleanup',
            priceFrom: 129,
            priceTo: null,
            description: 'Implementation on priority pages. Final quote depends on page count, CMS and access availability.',
        },
        {
            id: 'remediation-sprint',
            name: 'Full remediation sprint',
            priceFrom: 249,
            priceTo: null,
            description: 'Bundled technical remediation across multiple findings. Scope is confirmed after manual review.',
        },
    ],
    monthly: [
        {
            id: 'monitor',
            name: 'Monitor',
            price: 89,
            description: 'Rank and technical monitoring, monthly summary and priority alerts. No implementation included.',
        },
        {
            id: 'starter',
            name: 'Starter',
            price: 149,
            description: 'For small/local sites: monitoring, keyword tracking, technical follow-up and light on-page work.',
        },
        {
            id: 'growth',
            name: 'Growth',
            price: 249,
            description: 'Adds competitor, backlink and keyword-gap review plus a larger monthly optimization allowance.',
        },
        {
            id: 'pro',
            name: 'Pro',
            price: 399,
            description: 'For larger or e-commerce projects needing broader tracking, implementation and priority support.',
        },
    ],
    websiteBuilds: [
        { id: 'landing', name: 'Landing page', priceFrom: 149, description: 'A focused one-page site for a campaign, service or product.' },
        { id: 'portfolio', name: 'Portfolio', priceFrom: 229, description: 'A personal or creative portfolio with project presentation and contact flow.' },
        { id: 'business', name: 'Business website', priceFrom: 329, description: 'A professional small-business website with core pages, enquiry flow and basic SEO setup.' },
        { id: 'blog', name: 'Blog / publication', priceFrom: 349, description: 'A structured publishing website with categories, authoring and search-ready content templates.' },
        { id: 'store', name: 'Online store', priceFrom: 599, description: 'Product catalogue, cart and checkout foundation. Products and payment integrations affect scope.' },
        { id: 'custom', name: 'Custom web platform', priceFrom: 790, description: 'A tailored application, portal or workflow requiring discovery and a manually confirmed scope.' },
    ],
    supportOneOff: [
        { id: 'diagnosis', name: 'Initial diagnosis', price: '€29-€69', description: 'Review of the reported problem, technical checks and a clear repair recommendation.' },
        { id: 'small-fix', name: 'Small correction', price: '€49-€99', description: 'One bounded visual, content, configuration or plugin correction.' },
        { id: 'standard-fix', name: 'Standard repair', price: '€89-€199', description: 'A contained functional issue requiring investigation, implementation and verification.' },
        { id: 'complex-fix', name: 'Complex repair', price: '€199-€449', description: 'Multi-layer failure, custom-code repair or several connected issues.' },
        { id: 'performance', name: 'Speed optimization', price: '€99-€249', description: 'Caching, assets, database and delivery review with practical improvements.' },
        { id: 'malware', name: 'Malware cleanup and hardening', price: '€149-€349', description: 'Cleanup, access review, updates and reasonable hardening. Recovery depends on available backups.' },
        { id: 'migration', name: 'Website migration', price: '€129-€349', description: 'Migration to a new host or server, DNS guidance and launch verification.' },
        { id: 'hourly-wordpress', name: 'WordPress hourly work', price: '€29/hour', description: 'Suitable for small, clearly defined WordPress tasks.' },
        { id: 'hourly-custom', name: 'Custom development hourly work', price: '€39/hour', description: 'Frontend, backend, API, database or deployment work on a custom codebase.' },
    ],
    supportMonthly: [
        { id: 'wp-care', name: 'WordPress Care', platform: 'WordPress', price: 49, description: 'Core and plugin updates, backups, uptime checks and up to 30 minutes of small changes.' },
        { id: 'wp-business', name: 'WordPress Business', platform: 'WordPress', price: 89, description: 'Care features plus security checks, performance review and up to 90 minutes of changes.' },
        { id: 'woo-care', name: 'WooCommerce Care', platform: 'WooCommerce', price: 149, description: 'Store updates, backups, checkout checks and up to 2 hours of technical work.' },
        { id: 'custom-care', name: 'Custom Care', platform: 'Custom', price: 119, description: 'Dependency review, uptime checks, backups/deployment guidance and up to 90 minutes of work.' },
        { id: 'custom-growth', name: 'Custom Growth', platform: 'Custom', price: 229, description: 'Custom Care plus performance follow-up and up to 4 hours of development.' },
        { id: 'custom-priority', name: 'Custom Priority', platform: 'Custom', price: 399, description: 'Priority handling, proactive technical review and up to 8 hours of development.' },
    ],
    exclusions: [
        'Paid media, sponsored placements and paid backlinks are not included.',
        'Long-form content production and translation are quoted separately.',
        'Unusually high third-party data/API usage is confirmed before chargeable work starts.',
        'Final pricing is confirmed after scope review; applicable taxes are shown on the final quote or invoice.',
    ],
} as const;
